export default {
  cn: {
    workOrderInfo: {
      recalledBySender: '对方已撤回一条消息',
      Pmnum: '请输入正确商户号',
      descProT: '没有订单号？请在下方输入您的问题',
      Merchant: '商户号',
      tuozhuai: '将文件拖放到此处',
      huo: '或',
      duanji: '点击上传',
      enterTheMerchantNumber: '为了让技术支持快速定位您的问题， 请输入商户号',
      preQT: '描述您的问题',
      preQC: '请在下方详细描述您的问题，并提供相关凭证，我们会尽快为您解答。',
      creator: '创建人',
      myTicket: '我的咨询',
      workOrderTime: '工单时间',
      orderExisting: '该订单已经创建咨询，请刷新页面',
      mustSelectAContent: '必须选择一项内容',
      fileCount: '当前限制最多上传 5 个文件!',
      fileSize: '上传文件大小不能超过 30MB!',
      descriptionOfTheProblem: '请输入问题描述',
      textLimited: '请输入不超过1~200个字符',
      descProm: '请描述问题',
      tips: '提示',
      isAssociatedWithTwoOrders: '系统识别到该订单号关联多笔订单，请选择您想要咨询的订单',
      pleaseEnterYourReview: '请输入您的评价，将引导我们更好的为您服务',
      cancel: '取消',
      determine: '确定',
      uploadAttachments: '上传附件',
      sendOut: '发送',
      workOrder: '工单',
      reset: '重置',
      nailItAllTogether: '全部催一下',
      ticketCenter: '咨询中心',
      createAJob: '创建工单',
      jobList: '工单列表',
      workOrderDetails: '工单详情',
      transactionIssues: '订单问题',
      pleaseEnteOrderNumber: '请输入工单单号/交易单号/问题描述查找工单',
      pleaseEnterThePlatformOrderNumber: '请输入平台订单号/商户订单号/交易token号/本地收款账户号',
      exampleNumber: '例如：20240328154907210110402',
      lookup: '查找',
      consultationQuestions: '咨询问题',
      financialConsultation: '财务问题咨询',
      consultationOnProductionLineIssues: '产线问题咨询',
      complaint: '投诉与建议',
      MmcOperationQuestion: '商户平台操作问题',
      APIdockingIssues: '技术对接问题',
      other: '其他',
      detectedAnomaliesInThisTransaction: '平台系统检测到该笔存在异常，正在加急处理中，您可以点击创建咨询，来跟踪和沟通该笔订单的处理进度',
      transactionStatus: '交易状态',
      creationTime: '创建时间',
      amountOfMoney: '金额',
      countryRegion: '国家/地区',
      orderDetails: '订单信息',
      return: '返回',
      createConsultation: '发起咨询',
      viewProcessingDetails: '查看处理详情',
      transactionHasCreatedAWorkOrder: '该笔交易已创建工单',
      guessWhatYouWantToAsk: '猜您想要问',
      problemDescription: '问题描述',
      pleaseDescribeYourIssue: '请描述您的问题，并提供相关材料，我们会马上回复您。',
      relevantAttachments: '相关附件',
      dragAndDropFilesHereOrClickUpload: '将文件拖放到此处或点击上传',
      supportedExtensions: '支持的扩展名：jpg, pdf, doc, xls, mp4, txt, zip等，最多5个文件，单个文件大小不超过30M',
      yourLocalReceivingAccountNumber: '查询到这是您的本地收款账户号，请提供您想要咨询的订单相关的汇款凭证，并描述您的问题，我们会尽快为您解答。',
      describeYourIssue: '描述您的问题',
      noRelevantOrderLetterFound: '未找到相关订单信息，请核对您输入的订单信息是否正确。',
      describeYourIssueBelow: '您也可在下方描述您的问题，并提供相关凭证，我们会尽快为您解答。',
      orderHasBeenSuccessfullyCreated: '您的工单已成功创建，我们会尽快为您处理。',
      inProcess: '处理中',
      completed: '已完成',
      workOrderNumber: '工单单号',
      workOrderType: '工单类型',
      problemType: '问题类型',
      thisPenHasAnAbnormality: '该笔平台系统检测到该笔存在异常，正在加急处理中，若您有任何疑问，请描述您的问题，我们会及时回复您。',
      initiateAnotherInquiry: '再次发起问询，请描述您的问题，我们会及时回复您。',
      technicalSupportResponseTime: '技术支持响应时间为北京时间早10点~晚7点，当前非工作时间段，我们会在上班后，尽快回复您，感谢您的理解。',
      currentlyALargeNumberOfInquiries: '当前咨询人数较多，技术支持会尽快给您反馈，感谢您的理解。',
      provideOneOnOneServices: '尊敬的客户，我们将为您提供一对一服务，技术支持将在5分钟内受理您的需求',
      hurryUpPlease: '催一下',
      internalExpeditedProcessing: '已为您催促内部加急处理',
      endService: '结束服务',
      thankYouForYourInquiry: '服务结束，感谢您的咨询，请您对我们的服务进行评价。若您对本次咨询还有疑问，可以新建工单，再次提交咨询，请点击这里。',
      satisfactionEvaluation: '满意度评价',
      dissatisfied: '不满意',
      satisfied: '满意',
      great: '太赞了',
      iWantToRoast: '不满意，我要吐槽',
      areasForImprovement: '满意，有待改进的地方',
      iWantToComplimentYou: '太赞了，我想夸一夸',
      thankYouForYourReview: '感谢您的评价，祝您生活愉快，再见。',
      hasItSolvedYourProblem: '是否有解决您的问题',
      resolved: '已解决',
      unresolved: '未解决',
      sorryForNotSatisfyingYou: '很抱歉没让您满意，请描述您的问题，我们会尽快答复您。',
      iHavenTReceivedYourReplyYet: '亲爱的顾客，由于一直未能得到您的回复，我们将结束本次对话，请您对我们的服务进行评价。感谢您对我们平台的支持和理解！祝您生活愉快，再见！若您对本次咨询还有疑问，可以新建工单，再次提交咨询，请点击这里',
      allWorkOrders: '全部工单',
      thisMonthSWorkOrder: '本月工单',
      comparedToLastMonth: '较上月',
      pleaseEnterTheWorkOrderNumber: '请输入工单单号/交易单号查找工单',
      workOrderStatus: '工单状态',
      withinTheNormalProcessingTimeFrame: '所有工单都在正常的处理时效内，请您耐心等待。',
      ordersBeingProcessedInTheList: '列表中没有处理中的工单。',
      transactionOrderNo: '交易单号',
      completionTime: '完成时间',
      Action: '操作',
      notification: '通知',
      endList: '到底了',
      shortcutKeys: [
        {
          type: 'mac',
          text: '↵ 发送 / ⌘↵ 换行'
        },
        {
          type: 'win',
          text: 'Enter 发送，Ctrl+Enter 换行'
        }
      ],
    }
  },
  en: {
    workOrderInfo: {
      recalledBySender: 'A message has been recalled by the sender。',
      Pmnum: 'Please enter the correct merchant number',
      descProT: 'Do not have an order id? Please enter your question below.',
      Merchant: 'Merchant Account Number',
      tuozhuai: 'Drag and drop files here',
      huo: 'or',
      duanji: 'click to upload',
      enterTheMerchantNumber: 'In order for technical support team to quickly locate your question, please enter the merchant account number',
      preQT: 'Describe your question',
      preQC: 'please describe your question in detail, and provide the document if necessary. We will solve your question as soon as we can.',
      creator: 'Creator',
      myTicket: 'My Ticket',
      workOrderTime: 'Work Order Time',
      orderExisting: 'The order has been created, please refresh the page',
      mustSelectAContent: 'One item must be selected',
      fileCount: 'The current limit allows for a maximum of 5 files to be uploaded!',
      fileSize: 'The size of each uploaded file must not exceed 30MB!',
      descriptionOfTheProblem: 'Please enter a description of the problem',
      textLimited: 'Please enter a maximum of 1 to 200 characters',
      descProm: 'Please describe the problem',
      tips: 'Tips',
      isAssociatedWithTwoOrders: 'Several associated orders have been recognized by this order number detected by system. Please select the order you wish to inquire about.',
      pleaseEnterYourReview: 'Please enter your review, will guide Us to better serve you',
      cancel: 'Cancel',
      determine: 'Determine',
      uploadAttachments: 'Upload Attachments',
      sendOut: 'Send',
      workOrder: 'Tickets',
      reset: 'Reset',
      nailItAllTogether: 'Remind all Tickets',
      ticketCenter: 'Ticket Center',
      createAJob: 'Create Ticket',
      jobList: 'Ticket List',
      workOrderDetails: 'Ticket Details',
      transactionIssues: 'Transaction order question',
      pleaseEnteOrderNumber: 'Please enter the Ticket number, order number, or question description to search your ticket',
      pleaseEnterThePlatformOrderNumber: 'Please enter the trade order ID/merchant txn ID/transaction token number/local receiving account number(VA account)',
      exampleNumber: 'Example: 20240328154907210402',
      lookup: 'Search',
      consultationQuestions: 'Consulting question',
      financialConsultation: 'Finance related question',
      consultationOnProductionLineIssues: 'Production line related question',
      complaint: 'Complaints and suggestions',
      MmcOperationQuestion: 'Merchant platform question',
      APIdockingIssues: 'Technical integration question',
      other: 'Others',
      detectedAnomaliesInThisTransaction: "An anomaly related to this transaction has been detected by system and under the processing. You can click on “Create Ticket” to track and communicate the progress of this order's handling.",
      transactionStatus: 'Transaction Status',
      creationTime: 'Create Time',
      amountOfMoney: 'Amount',
      countryRegion: 'Country/Region',
      orderDetails: 'Order Information',
      return: 'Back',
      createConsultation: 'Create Ticket',
      viewProcessingDetails: 'View Processing Details',
      transactionHasCreatedAWorkOrder: 'This transaction has already created a ticket',
      guessWhatYouWantToAsk: 'You might ask',
      problemDescription: 'Question Description',
      pleaseDescribeYourIssue: 'Please describe your question and provide relevant materials, and we will reply to you as soon as possible.',
      relevantAttachments: 'Relavant Attachments',
      dragAndDropFilesHereOrClickUpload: 'Drag and drop files here or click to upload',
      supportedExtensions: 'Supported file extensions: jpg, pdf, doc, xls, mp4, txt, zip, etc., up to 5 files, 30MB in size per file.',
      yourLocalReceivingAccountNumber: 'We have found that this is your local receiving account number, please provide the remittance voucher related to the order you want to consult about, and describe your question, and we will reply you as soon as possible.',
      describeYourIssue: 'Describe your question',
      noRelevantOrderLetterFound: 'Order information not found, please check whether the order information you entered is correct.',
      describeYourIssueBelow: 'You can also describe your question below and provide relevant vouchers, and we will reply you as soon as possible.',
      orderHasBeenSuccessfullyCreated: 'Your ticket has been successfully created, and we will process it for you as soon as possible.',
      inProcess: 'In progress',
      completed: 'Completed',
      workOrderNumber: 'Ticket Number',
      workOrderType: 'Ticket Type',
      problemType: 'Question Type',
      thisPenHasAnAbnormality: 'An anomaly related to this transaction has been detected by system and under the processing. If you have any concern, please describe your question, and we will reply you in a timely manner.',
      initiateAnotherInquiry: 'For further inquiries, please describe your question, and we will reply you as soon as possible.',
      technicalSupportResponseTime: 'Technical support team response time is from 10 AM to 7 PM Beijing time. If you are currently outside of working hours, we will respond to you as soon as possible when we are back at work. Thank you for your understanding.',
      currentlyALargeNumberOfInquiries: 'Due to a high volume of inquiries, technical support team will get back to you as soon as possible. Thank you for your patience.',
      provideOneOnOneServices: 'Dear customer, we will prioritize provide service to you. Delicated technical support member will reply you within 5 minutes.',
      hurryUpPlease: 'Reminder',
      internalExpeditedProcessing: 'We have already push the progress internally for you.',
      endService: 'End Service',
      thankYouForYourInquiry: 'Service has ended. Thank you for your consultation. Please rate our service. If you still have questions about this consultation, you can submit further inquiry. Please click here.',
      satisfactionEvaluation: 'Satisfaction Rating',
      dissatisfied: 'Dissatisfied',
      satisfied: 'Satisfied',
      great: 'Amazing',
      iWantToRoast: 'Dissatisfied, I want to complain',
      areasForImprovement: "Satisfied, but there's space for improvement",
      iWantToComplimentYou: 'Amazing, I want to compliment',
      thankYouForYourReview: 'Thank you for your feedback. Wish you a pleasant life, goodbye.',
      hasItSolvedYourProblem: 'Has your question been resolved?',
      resolved: 'Resolved',
      unresolved: 'Not resolved',
      sorryForNotSatisfyingYou: 'We apologize for not meeting your satisfaction. Please describe your question, and we will reply to you as soon as possible.',
      iHavenTReceivedYourReplyYet: 'Dear customer, as we have not received a response from you, we will end this conversation. Please rate our service. Thank you for your support and understanding of our platform! We wish you a pleasant life, goodbye! If you still have questions about this consultation, you can submit further inquiry. Please click here.',
      allWorkOrders: 'All Tickets',
      thisMonthSWorkOrder: 'Tickets for This Month',
      comparedToLastMonth: 'Compared to Last Month',
      pleaseEnterTheWorkOrderNumber: 'Please enter the ticket number/transaction number to find the ticket',
      workOrderStatus: 'Ticket Status',
      withinTheNormalProcessingTimeFrame: 'All tickets are within the normal processing time frame. Please be patient and we will assist you shortly.',
      ordersBeingProcessedInTheList: 'There is no pending ticket in the list.',
      transactionOrderNo: 'Transaction Number',
      completionTime: 'Completion Time',
      Action: 'Action',
      notification: 'Notification',
      endList: 'End of List',
      shortcutKeys: [
        {
          type: 'mac',
          text: '↵ Send, ⌘↵ Enter'
        },
        {
          type: 'win',
          text: '↵ Send, Ctrl ↵ Enter'
        }
      ],
    }
  }
};
